name: Traffic Scraper Automation

on:
  schedule:
    # Runs 4 times an hour on "off-minutes" (7, 22, 37, 52) to bypass GitHub Actions server queues.
    # Runs ONLY between 02:00 UTC and 20:00 UTC.
    # 02:00 UTC = 5:00 AM EAT (Tanzania Time)
    # 20:00 UTC = 11:00 PM EAT (Tanzania Time)
    - cron: '7,22,37,52 2-20 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Pro-tip: Caches dependencies to make the bot run even faster!

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          FIREBASE_KEY_DATA: ${{ secrets.FIREBASE_KEY_JSON }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          echo "$FIREBASE_KEY_DATA" > firebase-key.json
          python scrape_traffic.py